# Generated by Django 4.1.7 on 2023-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='document',
            new_name='identity_card',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
