# Generated by Django 4.1.7 on 2023-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_document_student_identity_card_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='identity_card',
        ),
        migrations.AddField(
            model_name='student',
            name='identity_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IdentityNo'),
        ),
    ]
